# Generated by Django 2.2.9 on 2022-09-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220912_0938'),
        ('posts', '0004_auto_20220916_2105'),
    ]

    operations = [
    ]
