# Generated by Django 2.2.16 on 2022-10-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20221016_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
